### Health Check
GET https://nebius-endpoint.onrender.com/
Accept: application/json
X-NEBIUS-KEY: eyJhbGciOiJIUzI1NiIsImtpZCI6IlV6SXJWd1h0dnprLVRvdzlLZWstc0M1akptWXBvX1VaVkxUZlpnMDRlOFUiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiJnb29nbGUtb2F1dGgyfDEwNTU1MDIyMzE2ODE0MDEzNTYzNiIsInNjb3BlIjoib3BlbmlkIG9mZmxpbmVfYWNjZXNzIiwiaXNzIjoiYXBpX2tleV9pc3N1ZXIiLCJhdWQiOlsiaHR0cHM6Ly9uZWJpdXMtaW5mZXJlbmNlLmV1LmF1dGgwLmNvbS9hcGkvdjIvIl0sImV4cCI6MTkwMjM0OTA2NywidXVpZCI6ImExYjA1OWM0LWUwMWQtNDAyMS05MzE3LWY0YzJjZDBiZWQyOSIsIm5hbWUiOiJSRU5ERVIiLCJleHBpcmVzX2F0IjoiMjAzMC0wNC0xM1QyMjoxNzo0NyswMDAwIn0.dlUSpZQxAMZvidfztaiiKoEJ-wksCTDKUdZurujZ9E8


### Generate a new image
POST https://nebius-endpoint.onrender.com/generate
Content-Type: application/json
X-NEBIUS-KEY: eyJhbGciOiJIUzI1NiIsImtpZCI6IlV6SXJWd1h0dnprLVRvdzlLZWstc0M1akptWXBvX1VaVkxUZlpnMDRlOFUiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiJnb29nbGUtb2F1dGgyfDEwNTU1MDIyMzE2ODE0MDEzNTYzNiIsInNjb3BlIjoib3BlbmlkIG9mZmxpbmVfYWNjZXNzIiwiaXNzIjoiYXBpX2tleV9pc3N1ZXIiLCJhdWQiOlsiaHR0cHM6Ly9uZWJpdXMtaW5mZXJlbmNlLmV1LmF1dGgwLmNvbS9hcGkvdjIvIl0sImV4cCI6MTkwMjM0OTA2NywidXVpZCI6ImExYjA1OWM0LWUwMWQtNDAyMS05MzE3LWY0YzJjZDBiZWQyOSIsIm5hbWUiOiJSRU5ERVIiLCJleHBpcmVzX2F0IjoiMjAzMC0wNC0xM1QyMjoxNzo0NyswMDAwIn0.dlUSpZQxAMZvidfztaiiKoEJ-wksCTDKUdZurujZ9E8

{
  "prompt": "a woman in space",
  "width": 768,
  "height": 1024
}

### Check task status by ID (replace with your actual task ID)
GET https://nebius-endpoint.onrender.com/tasks/84e222c5-baeb-41d6-890e-e3c462105c37

### Get task result by ID (replace with your actual task ID)
GET https://nebius-endpoint.onrender.com/tasks/84e222c5-baeb-41d6-890e-e3c462105c37/result
Accept: application/json

### Check queue status
GET https://nebius-endpoint.onrender.com/queue/status
Accept: application/json

### Health Check
GET http://localhost:3000/
Accept: application/json
X-NEBIUS-KEY: eyJhbGciOiJIUzI1NiIsImtpZCI6IlV6SXJWd1h0dnprLVRvdzlLZWstc0M1akptWXBvX1VaVkxUZlpnMDRlOFUiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiJnb29nbGUtb2F1dGgyfDEwNTU1MDIyMzE2ODE0MDEzNTYzNiIsInNjb3BlIjoib3BlbmlkIG9mZmxpbmVfYWNjZXNzIiwiaXNzIjoiYXBpX2tleV9pc3N1ZXIiLCJhdWQiOlsiaHR0cHM6Ly9uZWJpdXMtaW5mZXJlbmNlLmV1LmF1dGgwLmNvbS9hcGkvdjIvIl0sImV4cCI6MTkwMjM0OTA2NywidXVpZCI6ImExYjA1OWM0LWUwMWQtNDAyMS05MzE3LWY0YzJjZDBiZWQyOSIsIm5hbWUiOiJSRU5ERVIiLCJleHBpcmVzX2F0IjoiMjAzMC0wNC0xM1QyMjoxNzo0NyswMDAwIn0.dlUSpZQxAMZvidfztaiiKoEJ-wksCTDKUdZurujZ9E8


### Generate a new image
POST http://localhost:3000/generate
Content-Type: application/json
X-NEBIUS-KEY: eyJhbGciOiJIUzI1NiIsImtpZCI6IlV6SXJWd1h0dnprLVRvdzlLZWstc0M1akptWXBvX1VaVkxUZlpnMDRlOFUiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiJnb29nbGUtb2F1dGgyfDEwNTU1MDIyMzE2ODE0MDEzNTYzNiIsInNjb3BlIjoib3BlbmlkIG9mZmxpbmVfYWNjZXNzIiwiaXNzIjoiYXBpX2tleV9pc3N1ZXIiLCJhdWQiOlsiaHR0cHM6Ly9uZWJpdXMtaW5mZXJlbmNlLmV1LmF1dGgwLmNvbS9hcGkvdjIvIl0sImV4cCI6MTkwMjM0OTA2NywidXVpZCI6ImExYjA1OWM0LWUwMWQtNDAyMS05MzE3LWY0YzJjZDBiZWQyOSIsIm5hbWUiOiJSRU5ERVIiLCJleHBpcmVzX2F0IjoiMjAzMC0wNC0xM1QyMjoxNzo0NyswMDAwIn0.dlUSpZQxAMZvidfztaiiKoEJ-wksCTDKUdZurujZ9E8

{
  "prompt": "a woman in space",
  "width": 768,
  "height": 1024
}

### Check task status by ID (replace with your actual task ID)
GET http://localhost:3000/tasks/f52e9dfd-b853-44df-b115-d49eed78303c

### Get task result by ID (replace with your actual task ID)
GET http://localhost:3000/tasks/0e398b98-5cc8-48c8-b217-4029037f93e7/result
Accept: application/json

### Check queue status
GET http://localhost:3000/queue/status
Accept: application/json



